### ISSUE TITLE
process corruption

### ISSUE THREAD

**Issue by fearless-pilgrim** [YuhuaXu/ImageMosaicing#2]
Respectful Author Xu:
  The method proposed in your article is brilliant, I am eager to accomplish your method on my data. But when I run your code to detect SIFT feature, the visual studio reminds me that there is something wrong that causes process corruption Since I have changed about 3-4 versions of OpenCV(2.4.0,2.4.3,4.4.0), I was wondering if something I miss, or whether you provided this code in the CMake version.

**Comment by YuhuaXu** [comment]
---opencv 2.4.0
---vs 2008

**Comment by fearless-pilgrim** [comment]
Appreciation for your kind help and sharing, I had recoding your code on Visual Studio 2019. But it seems not compatible between 2019 and 2008, anyway thanks for your help.
